services:
  postgres:
    image: postgres:latest
    container_name: portgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: prosopon
      POSTGRES_LOG_STATEMENT: 'all'
    volumes:
      - ~/data/postgres-data:/var/lib/postgresql/data
    network_mode: "host"
